### ISSUE TITLE
Incorrect support of NCO frequency offsets

### ISSUE THREAD

**Issue by ccsh23** [myriadrf/gr-limesdr#16]
Hi all,

I have already reported this on MyriadRF discourse, but maybe this is more official way, so just in case I will repeat it here as well.

I have tested gr-limesdr in full MIMO configuration (transmitting BPSK signals at two different frequencies with both TX channels and receiving them at the same time at the same frequencies with both RX channels) and found some obvious bugs in NCO offsets implementation.

I’ve been using sample rate of 6 MHz, center frequency of 2.44 GHz, NCO offsets of -2MHz and +2MHz for channels 0 and 1, respectively. Expected signal is shown in a picture below:
![bpsk_spectrum](https://user-images.githubusercontent.com/31406854/42603913-35c6f434-8570-11e8-8573-1441439b2fe6.png)

However, with spectrum analyzer I saw only signal from TX channel 1 actually present over-the-air, and none of the signals was correctly received.

All this works just fine with UHD and Osmocom blocks, so this is obviously gr-limesdr issue.

**Comment by gracid** [comment]
Thank you for pointing this out. This was fixed in [17e7996](https://github.com/myriadrf/gr-limesdr/commit/17e7996e2dd91054b446fa1c452b6d42a9d49d61) commit.
