### ISSUE TITLE
Changing frequency via GUI element does not work

### ISSUE THREAD

**Issue by gasparka** [myriadrf/gr-limesdr#2]
![screenshot from 2018-04-25 18-33-44](https://user-images.githubusercontent.com/16946258/39256312-3ceb2712-48b7-11e8-888b-57225e6b03ea.png)
Freq slider has no effect.

**Comment by 777arc** [comment]
Well for starters, source_impl.cc doesn't have a callback for setting the center_freq, and once that's created it would have to be registered at the top of the xml file as well.  Can LMS_SetLOFrequency even be changed after calling LMS_StartStream()?

**Comment by ztamosevicius** [comment]
As per README, Callback functions are under development.

**Comment by ztamosevicius** [comment]
Callback functions support implemented in 3efeadcbcfd26638d417c40a6ee033c08b00998e
