### ISSUE TITLE
LimeUtil -- find in device_handler.cc

### ISSUE THREAD

**Issue by 777arc** [myriadrf/gr-limesdr#20]
Line 73, should be 

LimeUtil --find

I.e. no space after the dashes.  Not set up to do a PR at the moment.

**Comment by gracid** [comment]
Thank you for pointing this out. This was changed in [17e7996](https://github.com/myriadrf/gr-limesdr/commit/17e7996e2dd91054b446fa1c452b6d42a9d49d61) commit.
