### ISSUE TITLE
Error on install. 

### ISSUE THREAD

**Issue by wgaylord** [myriadrf/gr-limesdr#21]
I already have GNU Radio installed using apt install gnuradio

https://gist.github.com/wgaylord/03bd87b234ca20490e9a3e3e13eb5b6b

**Comment by racerxdl** [comment]
```
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
```

Try install doxygen:

```
apt install doxygen

**Comment by racerxdl** [comment]
I think its probably a wrong instruction on gr-limesdr cmakelist.

**Comment by gracid** [comment]
Try installing gnuradio-dev package:
`apt install gnuradio-dev`
There was the same issue here: daniestevez/gr-satellites#15
