### ISSUE TITLE
Channel B flow graphs do not use correct callback channel parameter

### ISSUE THREAD

**Issue by heliochronix** [myriadrf/gr-limesdr#23]
When generating a flow graph within GRC, if CH0 is set to "B" in SISO mode, the generated code has "0" (Channel 0, or A) hard coded into all callback functions. This prevents any GRC generated code from modifying Channel B parameters while the flow graph is running. Manual editing of the code is required

Example to reproduce:
Using the signal_generator.grc example flow graph from gr-limesdr, change CH0 to "B" and attempt to run and adjust any channel specific parameters while running (TX Gain for example).

**Comment by gracid** [comment]
Both channels use correct callback parameters since  [17e7996](https://github.com/myriadrf/gr-limesdr/commit/17e7996e2dd91054b446fa1c452b6d42a9d49d61) commit.
