### ISSUE TITLE
make error inconsistent include path

### ISSUE THREAD

**Issue by oystercatcher** [myriadrf/gr-limesdr#24]

**Comment by oystercatcher** [comment]
SoapySDR, LimeSuite  installed from github
gr-limesdr    cmake ok but make failed 

failures above required  edit to  gr-limesdr/lib/common/device_handler.cc   
remove  lime from    
/* #include <lime/LMS7002M_parameters.h>  */
#include <LMS7002M_parameters.h>

**Comment by oystercatcher** [comment]
accident in closing

**Comment by gracid** [comment]
Thank you for pointing this out, this was fixed in [7c17016](https://github.com/myriadrf/gr-limesdr/commit/7c1701623d7f84079464069111e54ae53ecc0697) commit.
