### ISSUE TITLE
Oversample 'default' or '1' dont work

### ISSUE THREAD

**Issue by gasparka** [myriadrf/gr-limesdr#3]
'default' or '1':
![screenshot from 2018-04-25 18-38-25](https://user-images.githubusercontent.com/16946258/39256649-1b3973ca-48b8-11e8-822d-93b363ba67ac.png)

Others (2, 4):
![screenshot from 2018-04-25 18-33-44](https://user-images.githubusercontent.com/16946258/39256667-277dbee8-48b8-11e8-935d-a17dad9791c2.png)

**Comment by ztamosevicius** [comment]
Thanks, checking.

**Comment by ztamosevicius** [comment]
Fixed in 3efeadcbcfd26638d417c40a6ee033c08b00998e
