### ISSUE TITLE
relation of gr-limesdr to osmocon,homebrew-pothos/limesuite

### ISSUE THREAD

**Issue by mhaberler** [myriadrf/gr-limesdr#35]
we have this repo
we have the Soapy driver as outlined here:  https://discourse.myriadrf.org/t/guide-gnuradio-and-gqrx-with-limesdr-mini-on-macos-10-13/2702

which one is preferrable? why?

thanks in advance

Michael

**Comment by gracid** [comment]
Soapy driver is another abstraction layer over LMS hardware. This repo uses LimeSuite drivers directly and has some workarounds which don't exist in soapy. So I would say this one is preferable, though if you have multiple sdr devices or you want to use already existing flow graphs without changing anything soapy can be a solution to that.

**Comment by gracid** [comment]
Closing as I answered the question.
