### ISSUE TITLE
Bug: Transmit carrier remains active on gnuradio 'kill'

### ISSUE THREAD

**Issue by mhaberler** [myriadrf/gr-limesdr#36]
Sink exit should disable the transmitter.

**Comment by gracid** [comment]
Currently, there is workaround to switch PA paths when turning stream on/off or starting/stopping the flowgraph. It is kind of impossible to implement a solution on "kill" since it does not gracefully exit. The CW being transmitted is default LimeSuite behavior.

**Comment by gracid** [comment]
Currently, there is workaround to switch PA paths when turning stream on/off or starting/stopping the flowgraph. It is kind of impossible to implement a solution on "kill" since it does not gracefully exit. The CW being transmitted is default LimeSuite behavior.

**Comment by gracid** [comment]
Closing as I can't possibly fix this.
