### ISSUE TITLE
LimeSuite Source (RX) use with gr-ieee802-11wifi_rx.grc

### ISSUE THREAD

**Issue by calgaryy** [myriadrf/gr-limesdr#38]
Hi there,

trying to capture wifi packets with gr-ieee802-11 and my LimeSDR-Mini. I am asked for a Calibration Bandwidth and analog filter bandwidth however these terms aren't referenced anywhere that I can see. 

Has anyone attempted to do something similar?

Thanks

**Comment by gracid** [comment]
You could just use sample rate value for calibration bandwidth and analog filter bandwidth

**Comment by calgaryy** [comment]
Thank you for confirmation of this, I figured this out too 😊
