### ISSUE TITLE
Issue with latest GRC blocks

### ISSUE THREAD

**Issue by eokeeffe** [myriadrf/gr-limesdr#39]
Getting this error for some reason, I only just updated the repo and redid the cmake.

Traceback (most recent call last):
  File "top_block.py", line 358, in <module>
    main()
  File "top_block.py", line 346, in main
    tb = top_block_cls()
  File "top_block.py", line 163, in __init__
    self.limesdr_sink_0 = limesdr.sink('', 0, '', '')
TypeError: make() takes exactly 30 arguments (4 given)

Any clues as too what might be happening?

Ubuntu 16.04, GRC 3.7.10.1-62

**Comment by gracid** [comment]
It looks like a problem with version mismatch, as it python expects v1.0 xml blocks and you are using v2.0 xml blocks. After redoing cmake did you make and make install?

**Comment by eokeeffe** [comment]
I first did a make uninstall, cmake .. , make and then make install

I checked the xml blocks and they match the ones in the updated repo

**Comment by gracid** [comment]
Could you do it again(`make uninstall`, `make clean`, `cmake ..`, `make` and `make install`) and post the contents of console here?

**Comment by eokeeffe** [comment]
$ cmake ..
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Configuring Boost C++ Libraries...
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   thread
--   system
--   chrono
--   date_time
--   atomic
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") found components:  doxygen dot 
-- Configuring GNU Radio C++ Libraries...
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
Checking for GNU Radio Module: RUNTIME
-- Checking for module 'gnuradio-runtime'
--   Found gnuradio-runtime, version 3.7.11git
 * INCLUDES=/opt/gnuradio/include
 * LIBS=/opt/gnuradio/lib/libgnuradio-runtime.so;/opt/gnuradio/lib/libgnuradio-pmt.so
-- Found GNURADIO_RUNTIME: /opt/gnuradio/lib/libgnuradio-runtime.so;/opt/gnuradio/lib/libgnuradio-pmt.so  
GNURADIO_RUNTIME_FOUND = TRUE
Checking for GNU Radio Module: PMT
-- Checking for module 'gnuradio-runtime'
--   Found gnuradio-runtime, version 3.7.11git
 * INCLUDES=/opt/gnuradio/include
 * LIBS=/opt/gnuradio/lib/libgnuradio-runtime.so;/opt/gnuradio/lib/libgnuradio-pmt.so
-- Found GNURADIO_PMT: /opt/gnuradio/lib/libgnuradio-runtime.so;/opt/gnuradio/lib/libgnuradio-pmt.so  
GNURADIO_PMT_FOUND = TRUE
-- Configuring LimeSuite C++ Libraries...
-- Checking for module 'LimeSuite'
--   Found LimeSuite, version 19.01.0-ga58636db
-- Found LimeSuite: /usr/local/include/lime, /usr/local/lib/libLimeSuite.so
-- 
-- Checking for module SWIG
-- Found SWIG version 3.0.8.
-- Found SWIG: /usr/bin/swig3.0  
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.12", minimum required is "2") 
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.12", minimum required is "2") 
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/evan
$ ccmake .


$ make -j4
Scanning dependencies of target pygen_python_dd9b7
Scanning dependencies of target _limesdr_swig_doc_tag
Scanning dependencies of target gnuradio-limesdr
Scanning dependencies of target pygen_apps_9a6dd
[  8%] Built target pygen_apps_9a6dd
[  8%] Building CXX object swig/CMakeFiles/_limesdr_swig_doc_tag.dir/_limesdr_swig_doc_tag.cpp.o
[  8%] Generating __init__.pyc
Scanning dependencies of target doxygen_target
[ 13%] Generating documentation with doxygen
[ 17%] Generating __init__.pyo
[ 21%] Linking CXX executable _limesdr_swig_doc_tag
[ 21%] Built target pygen_python_dd9b7
[ 21%] Built target _limesdr_swig_doc_tag
Scanning dependencies of target limesdr_swig_swig_doc
[ 26%] Generating doxygen xml for limesdr_swig_doc docs
[ 30%] Generating python docstrings for limesdr_swig_doc
[ 30%] Built target doxygen_target
[ 30%] Built target limesdr_swig_swig_doc
Scanning dependencies of target _limesdr_swig_swig_tag
[ 34%] Building CXX object swig/CMakeFiles/_limesdr_swig_swig_tag.dir/_limesdr_swig_swig_tag.cpp.o
[ 39%] Linking CXX executable _limesdr_swig_swig_tag
[ 39%] Built target _limesdr_swig_swig_tag
[ 43%] Generating limesdr_swig.tag
Scanning dependencies of target limesdr_swig_swig_2d0df
[ 47%] Building CXX object swig/CMakeFiles/limesdr_swig_swig_2d0df.dir/limesdr_swig_swig_2d0df.cpp.o
[ 52%] Linking CXX executable limesdr_swig_swig_2d0df
Swig source
[ 56%] Building CXX object lib/CMakeFiles/gnuradio-limesdr.dir/source_impl.cc.o
[ 60%] Building CXX object lib/CMakeFiles/gnuradio-limesdr.dir/common/device_handler.cc.o
[ 65%] Building CXX object lib/CMakeFiles/gnuradio-limesdr.dir/sink_impl.cc.o
[ 65%] Built target limesdr_swig_swig_2d0df
Scanning dependencies of target pygen_swig_41007
[ 69%] Generating limesdr_swig.pyo
[ 73%] Generating limesdr_swig.pyc
[ 78%] Built target pygen_swig_41007
[ 82%] Linking CXX shared library libgnuradio-limesdr.so
[ 82%] Built target gnuradio-limesdr
Scanning dependencies of target _limesdr_swig
[ 86%] Building CXX object swig/CMakeFiles/_limesdr_swig.dir/limesdr_swigPYTHON_wrap.cxx.o
[ 91%] Linking CXX shared module _limesdr_swig.so
[100%] Built target _limesdr_swig
$ sudo make install
[ 17%] Built target gnuradio-limesdr
[ 26%] Built target _limesdr_swig_doc_tag
[ 34%] Built target limesdr_swig_swig_doc
[ 43%] Built target _limesdr_swig_swig_tag
[ 56%] Built target limesdr_swig_swig_2d0df
[ 69%] Built target pygen_swig_41007
[ 86%] Built target _limesdr_swig
[ 95%] Built target pygen_python_dd9b7
[ 95%] Built target pygen_apps_9a6dd
[100%] Built target doxygen_target
Install the project...
-- Install configuration: "Release"
-- Installing: /opt/gnuradio/lib/cmake/limesdr/limesdrConfig.cmake
-- Installing: /opt/gnuradio/include/limesdr/api.h
-- Installing: /opt/gnuradio/include/limesdr/source.h
-- Installing: /opt/gnuradio/include/limesdr/sink.h
-- Installing: /opt/gnuradio/lib/libgnuradio-limesdr.so
-- Set runtime path of "/opt/gnuradio/lib/libgnuradio-limesdr.so" to ""
-- Installing: /opt/gnuradio/lib/python2.7/dist-packages/limesdr/_limesdr_swig.so
-- Set runtime path of "/opt/gnuradio/lib/python2.7/dist-packages/limesdr/_limesdr_swig.so" to ""
-- Installing: /opt/gnuradio/lib/python2.7/dist-packages/limesdr/limesdr_swig.py
-- Installing: /opt/gnuradio/lib/python2.7/dist-packages/limesdr/limesdr_swig.pyc
-- Installing: /opt/gnuradio/lib/python2.7/dist-packages/limesdr/limesdr_swig.pyo
-- Installing: /opt/gnuradio/include/limesdr/limesdr/swig/limesdr_swig.i
-- Installing: /opt/gnuradio/include/limesdr/limesdr/swig/limesdr_swig_doc.i
-- Installing: /opt/gnuradio/lib/python2.7/dist-packages/limesdr/__init__.py
-- Installing: /opt/gnuradio/lib/python2.7/dist-packages/limesdr/__init__.pyc
-- Installing: /opt/gnuradio/lib/python2.7/dist-packages/limesdr/__init__.pyo
-- Installing: /opt/gnuradio/share/gnuradio/grc/blocks/limesdr_source.xml
-- Installing: /opt/gnuradio/share/gnuradio/grc/blocks/limesdr_sink.xml
-- Up-to-date: /opt/gnuradio/share/doc/gr-limesdr/xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/namespacegr_1_1limesdr.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/classgr_1_1limesdr_1_1source.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/namespacestd.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/sink__impl_8h.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/dir_7029781d67ed1229c585388ff8afbb99.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/structgr_1_1limesdr_1_1source__impl_1_1constant__data.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/classgr_1_1limesdr_1_1source__impl.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/index.xsd
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/main__page_8dox.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/group__defs_8dox.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/compound.xsd
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/combine.xslt
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/group__block.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/structgr_1_1limesdr_1_1sink__impl_1_1constant__data.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/source_8h.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/structdevice__handler_1_1device.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/dir_97aefd0d527b934f1d99a682da8fe6a9.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/dir_1ea122f7b94457c2332c194612c8b8fe.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/index.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/dir_d44c64559bbebec7f509842c48db8b23.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/classdevice__handler.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/namespacegr.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/source__impl_8h.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/indexpage.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/api_8h.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/sink_8h.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/device__handler_8h.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/classgr_1_1limesdr_1_1sink.xml
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/xml/classgr_1_1limesdr_1_1sink__impl.xml
-- Up-to-date: /opt/gnuradio/share/doc/gr-limesdr/html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classdevice__handler.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1sink__impl__inherit__graph.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/functions_func.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/functions.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/resize.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/globals_vars.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/open.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1source__impl__inherit__graph.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/graph_legend.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/globals_defs.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/api_8h__dep__incl.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/api_8h__incl.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1sink__inherit__graph.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/navtreeindex0.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/tab_b.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/device__handler_8h__dep__incl.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/group__defs_8dox.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/dir_97aefd0d527b934f1d99a682da8fe6a9_dep.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/sink__impl_8h.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/device__handler_8h_source.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/source__impl_8h__incl.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/main__page_8dox.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/inherit_graph_1.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/api_8h__incl.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/annotated.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/arrowright.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/nav_h.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/dir_000002_000000.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/source_8h__dep__incl.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/navtree.css
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/nav_g.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1sink__inherit__graph.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/api_8h.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/graph_legend.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/inherit_graph_1.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/hierarchy.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/device__handler_8h__dep__incl.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/namespacegr_1_1limesdr.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1source__inherit__graph.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/inherit_graph_0.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1source__impl-members.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/folderopen.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/api_8h__dep__incl.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1source.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/source_8h_source.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/sink__impl_8h_source.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/sync_off.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/device__handler_8h__incl.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/inherits.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/tab_s.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/doc.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/sink_8h_source.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/source__impl_8h.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1sink__impl__inherit__graph.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/tab_h.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/annotated_dup.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/tabs.css
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/sink__impl_8h__incl.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1source__inherit__graph.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/index.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/nav_f.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/dir_7029781d67ed1229c585388ff8afbb99.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/functions_type.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1sink__impl.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/device__handler_8h.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/graph_legend.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/source__impl_8h__incl.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/api_8h_source.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/source__impl_8h__incl.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/globals.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/modules.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/tab_a.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/bdwn.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classdevice__handler-members.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/sink_8h__incl.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/sink__impl_8h__incl.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1source__impl__inherit__graph.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1source__impl.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/device__handler_8h__dep__incl.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1source__impl__inherit__graph.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/group__block.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/device__handler_8h.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/namespacegr_1_1limesdr.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/source__impl_8h.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1sink__impl-members.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/inherit_graph_0.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1source-members.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1sink-members.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classdevice__handler.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/hierarchy.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1sink__impl.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/navtreedata.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/inherit_graph_0.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/sink_8h__dep__incl.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/sink__impl_8h__incl.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/sink_8h__incl.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/api_8h__incl.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classes.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/sink_8h.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/dir_1ea122f7b94457c2332c194612c8b8fe.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/dir_d44c64559bbebec7f509842c48db8b23.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/files.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/sink_8h__incl.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/jquery.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/dir_97aefd0d527b934f1d99a682da8fe6a9_dep.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/functions_vars.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/bc_s.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/arrowdown.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/dir_97aefd0d527b934f1d99a682da8fe6a9.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/source_8h__incl.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/sink__impl_8h.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1sink.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1source__inherit__graph.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/files.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/source__impl_8h_source.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/source_8h__incl.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/device__handler_8h__incl.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/device__handler_8h__incl.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/dir_000002_000003.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1sink__inherit__graph.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/api_8h.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/sink_8h__dep__incl.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/namespacegr.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/sink_8h__dep__incl.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1sink.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/source_8h__dep__incl.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/folderclosed.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/source_8h__incl.md5
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/namespacegr.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/splitbar.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/source_8h__dep__incl.map
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/inherit_graph_1.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/modules.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1sink__impl__inherit__graph.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/navtree.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/dir_97aefd0d527b934f1d99a682da8fe6a9_dep.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/source_8h.html
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/closed.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1source.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/doxygen.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/api_8h__dep__incl.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/classgr_1_1limesdr_1_1source__impl.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/dynsections.js
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/sync_on.png
-- Installing: /opt/gnuradio/share/doc/gr-limesdr/html/doxygen.css

**Comment by gracid** [comment]
Hmm, everything looks normal, can you try doing `sudo ldconfig` and checking if the issue persists?

**Comment by eokeeffe** [comment]
Just tried that, tring the ffm_rds.grc file I get

self.limesdr_source_0 = limesdr.source('', 0, '')
TypeError: make() takes exactly 30 arguments (3 given)

**Comment by gracid** [comment]
I'm not too familiar with nuances of installing in /opt/. Could you try checking if there are header files in /usr/local/include/limesdr/. You can try using this command:
`[ -f "/usr/local/include/limesdr/source.h" ] && echo "exists" `
If it does exist try doing `cmake --DCMAKE_INSTALL_PREFIX=/usr/local ../` and `sudo make install`

**Comment by gracid** [comment]
Cool, closing the issue.

**Comment by eokeeffe** [comment]
Thanks again gracid :)
