### ISSUE TITLE
Upgrade gr-limesdr to support GNU-Radio 3.8

### ISSUE THREAD

**Issue by gracid** [myriadrf/gr-limesdr#44]
There will be a lot of changes necessary to support GNU-Radio 3.8, currently it is still in [development](https://github.com/gnuradio/gnuradio/projects/1). Documentation to port to 3.8 is provided  [here](https://wiki.gnuradio.org/index.php./GNU_Radio_3.8_OOT_Module_Porting_Guide).

Right now it doesn't compile(#37) and the block description needs to be changed to yaml(#27).
At minimum, things that will need to be updated/changed are: CMake, python?, xml to yaml, examples.

**Comment by mormj** [comment]
Now that 3.8 is out, is this work currently in progress?

**Comment by mormj** [comment]
If not, I'd be happy to help out

**Comment by gracid** [comment]
Right now it isn't being worked on, it might be picked up on september.

**Comment by gracid** [comment]
It seems that basic RX is working (tested on clean ubuntu 18.04 with gnuradio maint-3.8 branch)

**Comment by eblot** [comment]
> It seems that basic RX is working (tested on clean ubuntu 18.04 with gnuradio maint-3.8 branch)

did you try with Python 3.x?

**Comment by gracid** [comment]
I only checked with python3 and only tested whether basic signal receive was working.

**Comment by eblot** [comment]
Great!

**Comment by 9600** [comment]
@gracid any update on when we'll have a release with full support?

**Comment by gracid** [comment]
I would say release would be coming next month since there were some issues.

**Comment by ra1nb0w** [comment]
any news?

**Comment by gracid** [comment]
The release will happen simultaneously with LimeSuite realease, the branches will probably stay as they are.

**Comment by ra1nb0w** [comment]
ok. thank you

**Comment by gracid** [comment]
Made the release [v3.0.1](https://github.com/myriadrf/gr-limesdr/releases/tag/v3.0.1)
