### ISSUE TITLE
Using gr-lte with LimeSDR

### ISSUE THREAD

**Issue by ergrillo** [myriadrf/gr-limesdr#45]
I already downloaded and install gr-lte for gnuradio on ubuntu 16, and i take a look at the example but i don't see nothing about interfacing with an SDR source. Can you help me to catch LTE stream from air with LimeSDR board?

**Comment by gracid** [comment]
On how to use the gr-limesdr blocks you can go read about here: [wiki](https://wiki.myriadrf.org/Gr-limesdr_Plugin_for_GNURadio). To use the coming data stream you can check his examples(as you already did) and read his publications.
Closing as this is non issue with gr-limesdr.
