### ISSUE TITLE
Tx Block(Sink) does not support  sample rate  above the 2MHz

### ISSUE THREAD

**Issue by rd15armas** [myriadrf/gr-limesdr#5]
Tx Block(Sink) does not support  sample rate  above the 2MHz

**Comment by ztamosevicius** [comment]
Sample rate above 2MHz is definitely supported. Why such a conclusion?

**Comment by rd15armas** [comment]
OK. I tested again and I have a request from you
Please adjust the sample rate 4M in FM transmitter.grc and FM Receiver.grc
and see the result with your own eyes

**Comment by ztamosevicius** [comment]
When you change sample rate in LimeSuite Source (RX), you have to change sample rate in Low Pass Filter and WX GUI FFT Sink blocks too. You have to adjust Decimation and Interpolation parameters in Rational Resampler block as well.

Check an example screenshot attached:
![image](https://user-images.githubusercontent.com/9800299/39576261-41af267e-4ee6-11e8-9e75-425c50858516.png)

**Comment by rd15armas** [comment]
Ok Please check the screenshots attached:  Where am I doing wrong..

[FM_transmitter.grc.zip](https://github.com/myriadrf/gr-limesdr/files/1973461/FM_transmitter.grc.zip)

screenshots 1:  sample rate=2.49M
![249](https://user-images.githubusercontent.com/29855246/39615665-241d5276-4f80-11e8-87fd-ccca02fbe96b.png)

screenshots 2:  sample rate=2.5M
![250](https://user-images.githubusercontent.com/29855246/39615714-5f01dc72-4f80-11e8-9d3b-4a71fdb96f1e.png)

**Comment by ztamosevicius** [comment]
Fixed in 3efeadcbcfd26638d417c40a6ee033c08b00998e
