### ISSUE TITLE
Compiling gr-limesdr for gnuradio 3.8.0.0

### ISSUE THREAD

**Issue by fcapozzi** [myriadrf/gr-limesdr#58]
Hi, cmake reports
`GnuRadio version required: >="3.7.8" < "3.8.0" found: "3.8.0.0"`
Is there any way to force compiling or i have to wait for a new version to be released ?
txn, Fabio,

**Comment by gracid** [comment]
Please switch branches from master to gr-3.8 by using `git checkout gr-3.8 ` command and clean your build directory before compiling again.

**Comment by FFY00** [comment]
@gracid is there a release supporting GNU Radio 3.8 planned soon?

**Comment by gracid** [comment]
The release has already been done: https://github.com/myriadrf/gr-limesdr/releases/tag/v3.0.1

**Comment by FFY00** [comment]
Ah, sorry. Missed it :)
