### ISSUE TITLE
TypeError: make() takes exactly 4 arguments (26 given)

### ISSUE THREAD

**Issue by LeLyfa** [myriadrf/gr-limesdr#59]
I'm trying to get the FM TX example working, but I get this error message:

```
Executing: /usr/bin/python2 /home/leon/Desktop/top_block.py

Error: failed to enable real-time scheduling.
Traceback (most recent call last):
  File "/home/leon/Desktop/top_block.py", line 91, in <module>
    main()
  File "/home/leon/Desktop/top_block.py", line 85, in main
    tb = top_block_cls()
  File "/home/leon/Desktop/top_block.py", line 61, in __init__
    60)
TypeError: make() takes exactly 4 arguments (26 given)
```

I know it has something to do with older versions, I also installed the package into /usr/local/ but it didn't help.

**Comment by gracid** [comment]
Try uninstalling all the packages through apt and/or make then check if some residual ones were leftover in these directories:

/usr/include/limesdr/*
/usr/lib/libgnuradio-limesdr.so*
/usr/lib/python2.7/dist-packages/limesdr/*
/usr/share/gnuradio/grc/blocks/limesdr_source.xml
/usr/share/gnuradio/grc/blocks/limesdr_sink.xml

Do the same for your /usr/local folders. After that try reinstalling or compiling from source again.

**Comment by LeLyfa** [comment]
Thank you.
