### ISSUE TITLE
What is the max gain?

### ISSUE THREAD

**Issue by hopkinskong** [myriadrf/gr-limesdr#61]
It seems that the limesdr block limited max gain to 60dB:
![image](https://user-images.githubusercontent.com/2718385/76992783-b582be00-6986-11ea-91b0-6bda61c977c5.png)

However, when I was using SDRangel to output some NFM signals, it seems it can go to 70dB.
![image](https://user-images.githubusercontent.com/2718385/76992927-faa6f000-6986-11ea-981e-451621d1f54f.png)

I can also confirm that setting 70dB in SDRangel had higher power output than 60dB in GNURadio.

What is the actual maximum gain for Tx?

**Comment by gracid** [comment]
I have update the maximum gain values to match LimeSuite with bf7e7d375ec95a5d24d14dea9008b5151b47249c commit. Right now they are in range of [0,73] dB, it is possible to bring them even higher but I won't get into that.

**Comment by kconkas** [comment]
@gracid the max sink gain is still limited to 60dB in https://github.com/myriadrf/gr-limesdr/blob/master/grc/limesdr_sink.xml#L442 and https://github.com/myriadrf/gr-limesdr/blob/master/grc/limesdr_sink.xml#L445. Is this intentional?

**Comment by 9600** [comment]
@gracid could you clarify, thanks.

**Comment by gracid** [comment]
Should be fixed with d7ba72128060158fc819fa4942fd3797bf501f31.
