### ISSUE TITLE
Reversed?

### ISSUE THREAD

**Issue by juzhang74** [myriadrf/gr-limesdr#63]
Hi,
in your sourcecode "lib/common/device_handler.cc", there is  

506 |  if (nco_freq > 0)
507 | cmix_mode = 0;
508 | else if (nco_freq < 0)
509 | cmix_mode = 1;

But with my test, it seems be reversed? Are you sure it's correct in your code?

**Comment by gracid** [comment]
Yes, with cmix mode = 0 signal is upconverted.
https://github.com/myriadrf/LimeSuite/blob/master/src/lime/LimeSuite.h#L681
