### ISSUE TITLE
pybombs install to prefix

### ISSUE THREAD

**Issue by lryindra** [myriadrf/gr-limesdr#9]
I installed limesuite from pybombs (example: pybombs -p myprefix install limesuite) that means that CMakeLists.txt could not find LIMESUITE_INCLUDE_DIRS, so I added a line to this code snippet:
find_path(LIMESUITE_INCLUDE_DIRS 
 NAMES LimeSuite.h
 PATHS ${LIMESUITE_PKG_INCLUDE_DIRS}
       /usr/include/lime
       /usr/local/include/lime
       ${CMAKE_INSTALL_PREFIX}/include/lime
)

**Comment by ztamosevicius** [comment]
Implemented in 3efeadcbcfd26638d417c40a6ee033c08b00998e
